### ISSUE TITLE
Only suggestion is the currently playing track

### ISSUE THREAD

**Issue by viceversaco** [berkon/track-suggestor#1]
Hello! I love this idea for this application but unfortunately I am running into some issues. On a Macbook OS level Mojave v10.14.6 with Traktor version 3.4.2. The only suggestion I am seeing is the currently playing master track. Any ideas?

**Comment by berkon** [comment]
@vicelversa, thanks for your hint. I must admit that I haven't tested with any Traktor version V3.x.x. I'm still on V2 (just don't want to touch a running system ;-) ). I'll check if I can install a V3 demo version on another machine.

**Comment by viceversaco** [comment]
Thanks for the prompt reply! Yes there might be some differences in the collection file between versions 2.x and 3.x. I believe you can run a trial / demo of version 3 which you can install side by side of version 2. Let me know if I can help in anyway :)

**Comment by berkon** [comment]
Your welcome @vicelversa!

Indeed there might be a thing you could try and which might help to find out what the problem is. After starting the tool, please press `<Cmd><Alt><Shift><i>`. A console window will appear and should show some debug messages. If there is an error message there, please let me know/post it here.

Thanks a lot!

**Comment by viceversaco** [comment]
Not seeing any errors unfortunately. I see that the collection loaded successfully and it detects when I load a new track in either deck. Here is an example entry from my collection file to compare:

`<ENTRY MODIFIED_DATE="2020/12/11" MODIFIED_TIME="23296" AUDIO_ID="ALgAERIiIyIiIiIiIiIiIiIyMiNJ6rq/6626u7/P763K/8vbvLv9//rcv/yuu9u/z+1oZv2o2GZa///4r///////////////////////9q////////////////////////u//vrf7/7//P+7/8+9/v/f79/lRVVlVERERVVVaGVodVR2Rml4qrqYmYmaqarbqaupmqmqu5q9z8zL38vPzMrv//zMvv3N+rzO///Jz///////////////////////mM///////////////////////5ZVVWVVRDRFZVRENFZFVDM0VFVEREVkVUQ0RVVVREVlRUMzRFVUMyIRAAAAAA==" TITLE="Boy" ARTIST="Odesza"><LOCATION DIR="/:Users/:robbie/:Music/:Albums/:ODESZA - A Moment Apart (Deluxe Edition)/:CD1/:" FILE="04 - Boy.mp3" VOLUME="Macintosh HD" VOLUMEID="Macintosh HD"></LOCATION>
<ALBUM TRACK="4" TITLE="A Moment Apart (Deluxe Edition)"></ALBUM>
<MODIFICATION_INFO AUTHOR_TYPE="user"></MODIFICATION_INFO>
<INFO BITRATE="320000" GENRE="Electro" LABEL="Counter Records" COVERARTID="051/TRJTZGBNS25QHAZQ4R5IBU4PVYEB" PLAYTIME="184" PLAYTIME_FLOAT="183.745300" IMPORT_DATE="2020/8/28" RELEASE_DATE="2018/11/30" FLAGS="12" FILESIZE="7248"></INFO>
<TEMPO BPM="69.999138" BPM_QUALITY="100.000000"></TEMPO>
<LOUDNESS PEAK_DB="0.589302" PERCEIVED_DB="-0.665794" ANALYZED_DB="-0.665794"></LOUDNESS>
<MUSICAL_KEY VALUE="5"></MUSICAL_KEY>
<CUE_V2 NAME="AutoGrid" DISPL_ORDER="0" TYPE="4" START="3332.887888" LEN="0.000000" REPEATS="-1" HOTCUE="0"></CUE_V2>
</ENTRY>`

**Comment by berkon** [comment]
Perfect, thanks for the extract of your collection! I'll check if there are differences. As soon as I have some time, I'll install a demo version of 3.x. I guess that's the easiest way to find out what's going wrong. But its good to know, that obviously the MIDI part, which detects the loaded tracks/artists works well.

**Comment by viceversaco** [comment]
I went ahead and tested on a Windows PC with Traktor version 2.11.31 and it seems to have the same issue. So not sure if its a collection file issue or something else is hanging up with matching tracks.

**Comment by berkon** [comment]
Now its getting really weird! Guess what! I tried the latest Traktor version 3 on a Windows machine and the tool works flawlessly. I'll prepare a debug build asap to get more output on the console and then I'll send it to you @vicelversa.

**Comment by berkon** [comment]
I found it @vicelversa! The problem is that the tool only show tracks which are rated to five stars. Looks like your example entry has no rating at all. My assumption was that for mixing I only want to get the "best" tracks which I rated best and of which I know that the crowd likes them. :-) Another thing is that I somehow had to find out only the tracks which have a valid grid on them (some tracks cannot be synced). Thus I abused the "Label" input field in the database and simply entered a "G" which means grid ;-) to tracks which can be synced accurately, so that I am able to find out which tracks I should show in the tool an which not.

Long story, short: I'll remove these limitations an post a new version asap. ;-)

**Comment by viceversaco** [comment]
Awesome! thank you so much for digging into it. I would say it would be nice to have some settings in the compiled app to adjust these parameters as I do see the benefit. I have limited knowledge on how to build / run / compile this type of app from your binaries. If you wanted to share that'd be great 😀

**Comment by berkon** [comment]
Oh, yeah that's a good idea, I'll put it in the settings! I just noticed that I didn't publish the build instructions in the Readme. But it is actually not very complicated, because this isn't really a binary. It is just Javascript code in combination with the so called "Electron" framework. So first you need to install NodeJS on your Mac from this location:

https://nodejs.org/en/download/

This installs the NPM (Node Package Manager) tool as well, which you need further down. I don't know how that is on the Mac, maybe you have to re-login to have the npm tool available via the path variable in the shell. Then download the code via this link and upack wherever you want:

https://github.com/berkon/track-suggestor/archive/refs/heads/master.zip

open the file renderer.js and remove the lines in the screenshot:

![image](https://user-images.githubusercontent.com/28842661/117198288-24b8ad00-ade9-11eb-837b-681ef2dad7a4.png)

as you can see I'm also hiding files which have HIDE_THIS as the genre type. This is a trick to prevent eg. loops or similar tracks from showing up.

Now change into the directory which you unpacked from a shell and type `npm install` and afterwards `npm start`. Now the tool sould start and hopefully not show the issue anymore. If the tool works as expected you can very easily create an installer for Mac by typing `npm run dist` in the shell. Then you should find an installable .dmg file in the `dist` subdirectory.

I must admit I wrote this down from my thoughts and didn't test it. But I think it should work. If not, give me a few days and I'll create an official build with the config option on the settings page. :-)

**Comment by viceversaco** [comment]
awesome thank you! Also, I've bumped your [thread over on the NI forum](https://www.native-instruments.com/forum/threads/track-suggestor-for-harmonic-mixing.421755/)s and some members had some good alternatives to using MIDI for the track data which might be worth looking into: https://github.com/ErikMinekus/traktor-api-client

Edit: I got it running with your instructions and with the changes everything is working as expected!

**Comment by berkon** [comment]
Hi @vicelversa, give it a try! The new version (1.1.0) is ready for download. :-) Let me know if it works.

**Comment by viceversaco** [comment]
thanks! I tried it out and didn't fill in any of the additional regex settings and it appeared over time I started receiving less and less matches for new tracks. I haven't had the time to dig into what was going on with it yet.
